name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  rb_linting:
    name: StandardRB Linting
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Run linting
      run: bundle exec standardrb

  specs:
    name: Tests
    runs-on: ubuntu-latest
    needs: [rb_linting]
    permissions: write-all
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install dependent libraries
      run: |
        sudo apt-get install libpq-dev

    - name: Setup database
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ci_test_db
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: |
        cd spec/dummy
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create
        bundle exec rails db:schema:load
        bundle exec rails db:test:prepare
        cd ../..

    - name: Run rspec
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ci_test_db
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: bundle exec rspec --tty --color --format documentation

    - uses: joshmfrankel/simplecov-check-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_suite_coverage: 99
